version: "3.9"

services:
  dev_db:
    image: postgres:16
    container_name: dev_db
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - dev_data:/var/lib/postgresql/data

  test_db:
    image: postgres:16
    container_name: test_db
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
    volumes:
      - test_data:/var/lib/postgresql/data

volumes:
  dev_data:
  test_data:
